# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
auth_header:
  use_cf_access: true
  cf_team: schlaubi
  cf_aud: 09ac6dbef247f5b375b67a284ab24f964c84f6347b2187dcb5228557602811cb

logger:
  default: info
  logs:
    custom_components.auth_header: debug
